---
abstract: 'A template generator getting different parts between pair of text'
author:
  - 'HyeonSeung Kim <sng2nara@hanmail.net>'
build_requires:
  Data::Dump: 0
  Data::Dumper: 0
  Test::More: 0
  re: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Reverse
requires:
  Algorithm::Diff: 0
  Moo: 0
  Scalar::Util: 0
  utf8: 0
resources:
  homepage: https://github.com/sng2c/Template-Reverse
  repository: git://github.com/sng2c/Template-Reverse.git
version: 0.143
